<template>
  <IssueTable
    v-if="rows.length"
    :rows="rows"
    :rows-count="pagination.count"
    :loading="loadingTable"
    @refresh="(pagination) => refresh(pagination)"
    :columns="allColumns"
    context-type="sprint"
  />
  <div
    v-else
    class="column flex-center"
    style="width: 100%; height: calc(100vh - 200px)"
  >
    <DocumentIcon :width="56" :height="56" />
    <h6>Нет задач</h6>
  </div>
</template>

<script setup lang="ts">
import IssueTable from 'src/modules/issue-list/components/IssueTable.vue';
import DocumentIcon from 'src/components/icons/DocumentIcon.vue';
import { ref, shallowRef, onMounted } from 'vue';

import { allColumns } from 'src/modules/issue-list/constants/tableColumns';

const rows = shallowRef<any[]>([]);
const pagination = ref<any>({});
const loadingTable = ref(false);

const refresh = async (pag: any) => {
  loadingTable.value = true;
  const data = {
    count: 30,
    limit: 25,
    offset: 0,
    issues: [
      {
        assignee_details: [
          {
            avatar: 'string',
            avatar_id: 'string',
            blocked_until: 'string',
            created_at: 'string',
            email: 'string',
            first_name: 'string',
            id: 'string',
            is_active: true,
            is_bot: true,
            is_integration: true,
            is_onboarded: true,
            is_superuser: true,
            last_active: 'string',
            last_name: 'string',
            status: 'string',
            status_emoji: 'string',
            status_end_date: 'string',
            telegram_id: 0,
            user_timezone: 'string',
            username: 'string',
          },
        ],
        attachment_count: 0,
        author_detail: {
          avatar: 'string',
          avatar_id: 'string',
          blocked_until: 'string',
          created_at: 'string',
          email: 'string',
          first_name: 'string',
          id: 'string',
          is_active: true,
          is_bot: true,
          is_integration: true,
          is_onboarded: true,
          is_superuser: true,
          last_active: 'string',
          last_name: 'string',
          status: 'string',
          status_emoji: 'string',
          status_end_date: 'string',
          telegram_id: 0,
          user_timezone: 'string',
          username: 'string',
        },
        blocked_issues: [
          {
            block: 'string',
            blocked_by: 'string',
            blocked_issue_detail: {
              id: 'string',
              name: 'string',
              priority: 'string',
              sequence_id: 0,
              short_url: 'string',
              state: 'string',
              state_detail: {
                color: 'string',
                default: true,
                description: 'string',
                group: 'string',
                id: 'string',
                name: 'string',
                project: 'string',
                sequence: 0,
                workspace: 'string',
              },
              url: 'string',
            },
            blocker_issue_detail: {
              id: 'string',
              name: 'string',
              priority: 'string',
              sequence_id: 0,
              short_url: 'string',
              state: 'string',
              state_detail: {
                color: 'string',
                default: true,
                description: 'string',
                group: 'string',
                id: 'string',
                name: 'string',
                project: 'string',
                sequence: 0,
                workspace: 'string',
              },
              url: 'string',
            },
            id: 'string',
          },
        ],
        blocker_issues: [
          {
            block: 'string',
            blocked_by: 'string',
            blocked_issue_detail: {
              id: 'string',
              name: 'string',
              priority: 'string',
              sequence_id: 0,
              short_url: 'string',
              state: 'string',
              state_detail: {
                color: 'string',
                default: true,
                description: 'string',
                group: 'string',
                id: 'string',
                name: 'string',
                project: 'string',
                sequence: 0,
                workspace: 'string',
              },
              url: 'string',
            },
            blocker_issue_detail: {
              id: 'string',
              name: 'string',
              priority: 'string',
              sequence_id: 0,
              short_url: 'string',
              state: 'string',
              state_detail: {
                color: 'string',
                default: true,
                description: 'string',
                group: 'string',
                id: 'string',
                name: 'string',
                project: 'string',
                sequence: 0,
                workspace: 'string',
              },
              url: 'string',
            },
            id: 'string',
          },
        ],
        completed_at: 'string',
        created_at: 'string',
        desc_highlighted: 'string',
        description_html: 'string',
        description_stripped: 'string',
        description_type: 0,
        draft: true,
        estimate_point: 0,
        id: 'string',
        issue_inline_attachments: [
          {
            content_type: 'string',
            id: 'string',
            name: 'string',
            size: 0,
          },
        ],
        issue_link: [
          {
            created_at: 'string',
            id: 'string',
            title: 'string',
            updated_at: 'string',
            url: 'string',
          },
        ],
        label_details: [
          {
            color: 'string',
            description: 'string',
            id: 'string',
            name: 'string',
            project: 'string',
          },
        ],
        link_count: 0,
        linked_issues_count: 0,
        name: 'string',
        name_highlighted: 'string',
        parent: 'string',
        parent_detail: {
          id: 'string',
          name: 'string',
          priority: 'string',
          sequence_id: 0,
          short_url: 'string',
          state: 'string',
          state_detail: {
            color: 'string',
            default: true,
            description: 'string',
            group: 'string',
            id: 'string',
            name: 'string',
            project: 'string',
            sequence: 0,
            workspace: 'string',
          },
          url: 'string',
        },
        priority: 'string',
        project: 'string',
        project_detail: {
          cover_image: 'string',
          current_user_membership: {
            id: 'string',
            is_default_assignee: true,
            is_default_watcher: true,
            member: {
              avatar: 'string',
              avatar_id: 'string',
              blocked_until: 'string',
              created_at: 'string',
              email: 'string',
              first_name: 'string',
              id: 'string',
              is_active: true,
              is_bot: true,
              is_integration: true,
              is_onboarded: true,
              is_superuser: true,
              last_active: 'string',
              last_name: 'string',
              status: 'string',
              status_emoji: 'string',
              status_end_date: 'string',
              telegram_id: 0,
              user_timezone: 'string',
              username: 'string',
            },
            member_id: 'string',
            project: 'string',
            project_id: 'string',
            role: 0,
            workspace_admin: true,
          },
          default_assignees: ['string'],
          default_assignees_details: [
            {
              id: 'string',
              is_default_assignee: true,
              is_default_watcher: true,
              member: {
                avatar: 'string',
                avatar_id: 'string',
                blocked_until: 'string',
                created_at: 'string',
                email: 'string',
                first_name: 'string',
                id: 'string',
                is_active: true,
                is_bot: true,
                is_integration: true,
                is_onboarded: true,
                is_superuser: true,
                last_active: 'string',
                last_name: 'string',
                status: 'string',
                status_emoji: 'string',
                status_end_date: 'string',
                telegram_id: 0,
                user_timezone: 'string',
                username: 'string',
              },
              member_id: 'string',
              project: {
                cover_image: 'string',
                current_user_membership: {
                  id: 'string',
                  is_default_assignee: true,
                  is_default_watcher: true,
                  member: {
                    avatar: 'string',
                    avatar_id: 'string',
                    blocked_until: 'string',
                    created_at: 'string',
                    email: 'string',
                    first_name: 'string',
                    id: 'string',
                    is_active: true,
                    is_bot: true,
                    is_integration: true,
                    is_onboarded: true,
                    is_superuser: true,
                    last_active: 'string',
                    last_name: 'string',
                    status: 'string',
                    status_emoji: 'string',
                    status_end_date: 'string',
                    telegram_id: 0,
                    user_timezone: 'string',
                    username: 'string',
                  },
                  member_id: 'string',
                  project: 'string',
                  project_id: 'string',
                  role: 0,
                  workspace_admin: true,
                },
                default_assignees: ['string'],
                default_assignees_details: [
                  {
                    id: 'string',
                    is_default_assignee: true,
                    is_default_watcher: true,
                    member: {
                      avatar: 'string',
                      avatar_id: 'string',
                      blocked_until: 'string',
                      created_at: 'string',
                      email: 'string',
                      first_name: 'string',
                      id: 'string',
                      is_active: true,
                      is_bot: true,
                      is_integration: true,
                      is_onboarded: true,
                      is_superuser: true,
                      last_active: 'string',
                      last_name: 'string',
                      status: 'string',
                      status_emoji: 'string',
                      status_end_date: 'string',
                      telegram_id: 0,
                      user_timezone: 'string',
                      username: 'string',
                    },
                    member_id: 'string',
                    project: 'string',
                    project_id: 'string',
                    role: 0,
                    workspace_admin: true,
                  },
                ],
                default_watchers: ['string'],
                default_watchers_details: [
                  {
                    id: 'string',
                    is_default_assignee: true,
                    is_default_watcher: true,
                    member: {
                      avatar: 'string',
                      avatar_id: 'string',
                      blocked_until: 'string',
                      created_at: 'string',
                      email: 'string',
                      first_name: 'string',
                      id: 'string',
                      is_active: true,
                      is_bot: true,
                      is_integration: true,
                      is_onboarded: true,
                      is_superuser: true,
                      last_active: 'string',
                      last_name: 'string',
                      status: 'string',
                      status_emoji: 'string',
                      status_end_date: 'string',
                      telegram_id: 0,
                      user_timezone: 'string',
                      username: 'string',
                    },
                    member_id: 'string',
                    project: 'string',
                    project_id: 'string',
                    role: 0,
                    workspace_admin: true,
                  },
                ],
                emoji: '0',
                id: 'string',
                identifier: 'string',
                is_favorite: true,
                logo: 'string',
                name: 'string',
                name_highlighted: 'string',
                project_lead: 'string',
                public: true,
                total_members: 0,
                url: 'string',
                workspace: 'string',
              },
              project_id: 'string',
              role: 0,
              workspace_admin: true,
            },
          ],
          default_watchers: ['string'],
          default_watchers_details: [
            {
              id: 'string',
              is_default_assignee: true,
              is_default_watcher: true,
              member: {
                avatar: 'string',
                avatar_id: 'string',
                blocked_until: 'string',
                created_at: 'string',
                email: 'string',
                first_name: 'string',
                id: 'string',
                is_active: true,
                is_bot: true,
                is_integration: true,
                is_onboarded: true,
                is_superuser: true,
                last_active: 'string',
                last_name: 'string',
                status: 'string',
                status_emoji: 'string',
                status_end_date: 'string',
                telegram_id: 0,
                user_timezone: 'string',
                username: 'string',
              },
              member_id: 'string',
              project: {
                cover_image: 'string',
                current_user_membership: {
                  id: 'string',
                  is_default_assignee: true,
                  is_default_watcher: true,
                  member: {
                    avatar: 'string',
                    avatar_id: 'string',
                    blocked_until: 'string',
                    created_at: 'string',
                    email: 'string',
                    first_name: 'string',
                    id: 'string',
                    is_active: true,
                    is_bot: true,
                    is_integration: true,
                    is_onboarded: true,
                    is_superuser: true,
                    last_active: 'string',
                    last_name: 'string',
                    status: 'string',
                    status_emoji: 'string',
                    status_end_date: 'string',
                    telegram_id: 0,
                    user_timezone: 'string',
                    username: 'string',
                  },
                  member_id: 'string',
                  project: 'string',
                  project_id: 'string',
                  role: 0,
                  workspace_admin: true,
                },
                default_assignees: ['string'],
                default_assignees_details: [
                  {
                    id: 'string',
                    is_default_assignee: true,
                    is_default_watcher: true,
                    member: {
                      avatar: 'string',
                      avatar_id: 'string',
                      blocked_until: 'string',
                      created_at: 'string',
                      email: 'string',
                      first_name: 'string',
                      id: 'string',
                      is_active: true,
                      is_bot: true,
                      is_integration: true,
                      is_onboarded: true,
                      is_superuser: true,
                      last_active: 'string',
                      last_name: 'string',
                      status: 'string',
                      status_emoji: 'string',
                      status_end_date: 'string',
                      telegram_id: 0,
                      user_timezone: 'string',
                      username: 'string',
                    },
                    member_id: 'string',
                    project: 'string',
                    project_id: 'string',
                    role: 0,
                    workspace_admin: true,
                  },
                ],
                default_watchers: ['string'],
                default_watchers_details: [
                  {
                    id: 'string',
                    is_default_assignee: true,
                    is_default_watcher: true,
                    member: {
                      avatar: 'string',
                      avatar_id: 'string',
                      blocked_until: 'string',
                      created_at: 'string',
                      email: 'string',
                      first_name: 'string',
                      id: 'string',
                      is_active: true,
                      is_bot: true,
                      is_integration: true,
                      is_onboarded: true,
                      is_superuser: true,
                      last_active: 'string',
                      last_name: 'string',
                      status: 'string',
                      status_emoji: 'string',
                      status_end_date: 'string',
                      telegram_id: 0,
                      user_timezone: 'string',
                      username: 'string',
                    },
                    member_id: 'string',
                    project: 'string',
                    project_id: 'string',
                    role: 0,
                    workspace_admin: true,
                  },
                ],
                emoji: '0',
                id: 'string',
                identifier: 'string',
                is_favorite: true,
                logo: 'string',
                name: 'string',
                name_highlighted: 'string',
                project_lead: 'string',
                public: true,
                total_members: 0,
                url: 'string',
                workspace: 'string',
              },
              project_id: 'string',
              role: 0,
              workspace_admin: true,
            },
          ],
          emoji: '0',
          id: 'string',
          identifier: 'string',
          is_favorite: true,
          logo: 'string',
          name: 'string',
          name_highlighted: 'string',
          project_lead: 'string',
          public: true,
          total_members: 0,
          url: 'string',
          workspace: 'string',
        },
        sequence_id: 0,
        short_url: 'string',
        sprints: [
          {
            description: 'string',
            end_date: 'string',
            id: 'string',
            name: 'string',
            sequence_id: 0,
            short_url: 'string',
            start_date: 'string',
            stats: {
              all_issues: 0,
              cancelled: 0,
              completed: 0,
              in_progress: 0,
              pending: 0,
            },
            url: 'string',
          },
        ],
        start_date: 'string',
        state: 'string',
        state_detail: {
          color: 'string',
          default: true,
          description: 'string',
          group: 'string',
          id: 'string',
          name: 'string',
          project: 'string',
          sequence: 0,
          workspace: 'string',
        },
        sub_issues_count: 0,
        target_date: 'string',
        updated_at: 'string',
        updated_by: 'string',
        url: 'string',
        watcher_details: [
          {
            avatar: 'string',
            avatar_id: 'string',
            blocked_until: 'string',
            created_at: 'string',
            email: 'string',
            first_name: 'string',
            id: 'string',
            is_active: true,
            is_bot: true,
            is_integration: true,
            is_onboarded: true,
            is_superuser: true,
            last_active: 'string',
            last_name: 'string',
            status: 'string',
            status_emoji: 'string',
            status_end_date: 'string',
            telegram_id: 0,
            user_timezone: 'string',
            username: 'string',
          },
        ],
        workspace: 'string',
        workspace_detail: {
          id: 'string',
          logo: 'string',
          name: 'string',
          owner_id: 'string',
          slug: 'string',
          url: 'string',
        },
      },
    ],
  };

  for (let i = 0; i < 30; ++i) {
    data.issues.push(data.issues[0]);
  }

  rows.value = data.issues;
  console.log(rows.value);
  pagination.value = { ...pag };
  pagination.value.count = data.count;
  pagination.value.limit = data.limit;
  pagination.value.offset = data.offset;

  loadingTable.value = false;
};

onMounted(async () => {
  refresh({});
});
</script>
