export const CLOUD_THEMES = {
  morning: {
    el: '#vanta-clouds-bg',
    mouseControls: true,
    touchControls: true,
    gyroControls: false,
    minHeight: 200.0,
    minWidth: 200.0,
    backgroundColor: 0xf3efe9,
    skyColor: 0x8fbfd1,
    cloudColor: 0xede0d4,
    cloudShadowColor: 0x6e8299,
    sunColor: 0xffd9a8,
    sunGlareColor: 0xefb185,
    sunlightColor: 0xdda97e,
    speed: 1.5,
  },
  afternoon: {
    el: '#vanta-clouds-bg',
    mouseControls: true,
    touchControls: true,
    gyroControls: false,
    minHeight: 200.0,
    minWidth: 200.0,
    backgroundColor: 0xeef2f6,
    skyColor: 0x8bb0c9,
    cloudColor: 0xe3e9ef,
    cloudShadowColor: 0x59728a,
    sunColor: 0xf2e6cc,
    sunGlareColor: 0xc4ab8a,
    sunlightColor: 0xa89272,
    speed: 1.5,
  },
  evening: {
    el: '#vanta-clouds-bg',
    mouseControls: true,
    touchControls: true,
    gyroControls: false,
    minHeight: 200.0,
    minWidth: 200.0,
    backgroundColor: 0x2e2438,
    skyColor: 0xcfa084,
    cloudColor: 0xf2d9c4,
    cloudShadowColor: 0x6b5a72,
    sunColor: 0xffe2b8,
    sunGlareColor: 0xe8a672,
    sunlightColor: 0xc97f55,
    speed: 1.5,
  },
  night: {
    el: '#vanta-clouds-bg',
    mouseControls: true,
    touchControls: true,
    gyroControls: false,
    minHeight: 200.0,
    minWidth: 200.0,
    backgroundColor: 0x0a0f1e,
    skyColor: 0x141c33,
    cloudColor: 0x4a4f68,
    cloudShadowColor: 0x0d1526,
    sunColor: 0xdfe6f5,
    sunGlareColor: 0x2e3a55,
    sunlightColor: 0x3d4a6b,
    speed: 1.5,
  },
};
