export const ROLES = {
  workspace: {
    owner: [
      'ws-settings',
      'delete-ws',
      'create-project',
      'delete-project',
      'add-comment',
      'create-issue',
      'change-issue-primary',
      'change-issue-secondary',
      'change-issue-basic',
      'delete-issue',
      'project-settings',
      'show-project-popup',
      'jira-import',
      'show-project',
      'transfer-issue',
      'add-linked-issue',
      'add-sub-issue',
      'show-ws',
      'create-form',
      'change-lead-ws',
      'change-issue-status',
      'delete-issue-comment',
      'edit-document',
      'create-sprint',
      'show-sprint-popup',
      'show-sprints-nav',
      'show-forms-nav',
      'change-sprint',
      'edit-sprint',
      'delete-sprint',
      'edit-sprint-folders',
      'create-tag',
    ],
    admin: [
      'ws-settings',
      'create-project',
      'delete-project',
      'add-comment',
      'create-issue',
      'change-issue-primary',
      'change-issue-secondary',
      'change-issue-basic',
      'delete-issue',
      'project-settings',
      'show-project-popup',
      'jira-import',
      'show-project',
      'transfer-issue',
      'add-linked-issue',
      'add-sub-issue',
      'show-ws',
      'create-form',
      'change-issue-status',
      'delete-issue-comment',
      'edit-document',
      'create-sprint',
      'show-sprint-popup',
      'show-sprints-nav',
      'show-forms-nav',
      'change-sprint',
      'edit-sprint',
      'delete-sprint',
      'edit-sprint-folders',
      'create-tag',
    ],
    member: ['show-ws', 'edit-document', 'show-sprints-nav'],
    guest: ['show-ws'],
  },
  project: {
    lead: [
      'delete-project',
      'add-comment',
      'create-issue',
      'change-issue-primary',
      'change-issue-secondary',
      'change-issue-basic',
      'delete-issue',
      'project-settings',
      'show-project-popup',
      'change-lead-project',
      'show-project',
      'transfer-issue',
      'add-linked-issue',
      'add-sub-issue',
      'add-to-fav',
      'change-issue-status',
      'delete-issue-comment',
    ],
    admin: [
      'add-comment',
      'create-issue',
      'change-issue-primary',
      'change-issue-secondary',
      'change-issue-basic',
      'delete-issue',
      'project-settings',
      'show-project-popup',
      'show-project',
      'transfer-issue',
      'add-linked-issue',
      'add-sub-issue',
      'add-to-fav',
      'change-issue-status',
      'delete-issue-comment',
    ],
    member: [
      'add-comment',
      'create-issue',
      'change-issue-basic',
      'show-project-popup',
      'show-project',
      'change-issue-status',
      'add-to-fav',
      'transfer-issue',
    ],
    guest: ['show-project-popup', 'show-project', 'show-comment', 'add-to-fav'],
  },
  issue: {
    author: [
      'add-comment',
      'delete-issue',
      'create-issue',
      'change-issue-primary',
      'change-issue-secondary',
      'change-issue-basic',
      'transfer-issue',
      'add-linked-issue',
      'add-sub-issue',
      'change-issue-status',
    ],
    assignee: [
      'add-comment',
      'create-issue',
      'change-issue-secondary',
      'change-issue-basic',
      'change-issue-status',
    ],
  },
};
