import { CalendarEvent } from '../types/calendar';

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: '1:created',
    issueId: '1',
    type: 'created',
    title: 'Создание задачи',
    date: new Date('2026-01-03'),
    color: '#26B5CE',
    isAllDay: true,
    issueUrl: '/issues/1',
  },
  {
    id: '1:target',
    issueId: '1',
    type: 'target',
    title: 'Дедлайн задачи',
    date: new Date('2026-01-10'),
    color: '#05BD8D',
    isAllDay: true,
    issueUrl: '/issues/1',
  },
  {
    id: '2:created',
    issueId: '2',
    type: 'created',
    title: 'Новая задача',
    date: new Date('2026-01-08'),
    color: '#26B5CE',
    isAllDay: true,
    issueUrl: '/issues/2',
  },
  {
    id: '2:completed',
    issueId: '2',
    type: 'completed',
    title: 'Задача завершена',
    date: new Date('2026-01-15'),
    color: '#F2994A',
    isAllDay: true,
    issueUrl: '/issues/2',
  },
  {
    id: '3:created',
    issueId: '3',
    type: 'created',
    title: 'Подготовить отчёт',
    date: new Date('2026-01-18'),
    color: '#26B5CE',
    isAllDay: true,
    issueUrl: '/issues/3',
  },
  {
    id: '3:canceled',
    issueId: '3',
    type: 'canceled',
    title: 'Задача отменена',
    date: new Date('2026-01-20'),
    color: '#DC3E3E',
    isAllDay: true,
    issueUrl: '/issues/3',
  },
  {
    id: '4:target',
    issueId: '4',
    type: 'target',
    title: 'Сдать макеты',
    date: new Date('2026-01-22'),
    color: '#05BD8D',
    isAllDay: true,
    issueUrl: '/issues/4',
  },
  {
    id: '5:completed',
    issueId: '5',
    type: 'completed',
    title: 'Релиз фичи',
    date: new Date('2026-01-28'),
    color: '#F2994A',
    isAllDay: true,
    issueUrl: '/issues/5',
  },
];
