export const DEFAULT_VIEW_PROPS = {
  showEmptyGroups: false,
  showSubIssues: true,
  showOnlyActive: false,
  autoSave: false,
  issueView: 'list',
  filters: {
    order_by: 'sequence_id',
    group_by: 'none',
    orderDesc: true,
    states: [],
    workspaces: [],
    projects: [],
    assignedToMe: false,
    watchedToMe: false,
    authoredToMe: false,
  },
  group_tables_hide: {},
  columns_to_show: [
    'name',
    'priority',
    'state',
    'target_date',
    'created_at',
    'updated_at',
    'author',
    'assignees',
    'labels',
    'sub_issues_count',
    'linked_issues_count',
    'link_count',
    'attachment_count',
  ],
  page_size: 25,
  draft: true,
};
